modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/cofl/ClimateAdjuster/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ClimateAdjuster"
logoFile="climate_adjuster.png"

[[mods]]
modId="climateadjuster"
version="${file.jarVersion}"
displayName="Example Mod"
authors="cofl"

description='''
Allows patching biome climate data with a custom configuration. Schema for config/climateadjuster/climate_data.json is:

```typescript
{
    "namespace:biomename": { // optional
        "temperature": number | null, // optional. See <https://minecraft.gamepedia.com/Biome#Temperature>. Range: [-0.5, 2.0]
        "downfall": number | null, // optional. Range: [0.0, 1.0]
        "precipitation": "none" | "rain" | "snow" | null // optional.
    }
}
```

If using Serene Seasons, prefer the "rain" precipitation type.
'''

[[dependencies.climateadjuster]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.climateadjuster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
